### ISSUE TITLE
Expose portainer and traefik dashboard

### ISSUE THREAD

**Issue by fabifont** [DoTheEvo/Traefik-v2-examples#4]
Hi, when I try to expose:
- ~~portainer: it asks for basic auth as it should, after the verification is successful it shows `Not found`~~ [fixed, see comments]
- ~~traefik dashboard: it doesn't even asks for basic auth and shows `404 not found`~~ [fixed and updated docker-compose.yml]

Here is my `traefik.toml`:
```
[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encr.acme]
  email = "myemail@mailbox.org"
  storage = "acme.json"
  [certificatesResolvers.lets-encr.acme.dnsChallenge]
    provider = "cloudflare"
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[log]
  level = "DEBUG"
```

And this is my `docker-compose.yml` [fixed]:
```
version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml:ro
      - ./users_credentials:/users_credentials:ro
      - ./acme.json:/acme.json
    labels:
      - traefik.enable=true
      # DNS CHALLENGE
      - traefik.http.routers.traefik.tls.certresolver=lets-encr
      - traefik.http.routers.traefik.tls.domains[0].main=*.$MY_DOMAIN
      - traefik.http.routers.traefik.tls.domains[0].sans=$MY_DOMAIN
      # DASHBOARD
      - traefik.http.routers.traefik.rule=Host(`traefik.$MY_DOMAIN`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.middlewares=auth-middleware
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.middlewares.auth-middleware.basicauth.usersfile=/users_credentials
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=Host(`portainer.$MY_DOMAIN`)
      - traefik.http.routers.portainer.tls.certresolver=lets-encr
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    depends_on:
      - traefik
    restart: unless-stopped

  whoami:
    image: containous/whoami
    container_name: whoami
    hostname: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.rule=Host(`whoami.$MY_DOMAIN`)
      - traefik.http.routers.whoami.tls.certresolver=lets-encr
    depends_on:
      - traefik
    restart: unless-stopped

networks:
  default:
    name: $DEFAULT_NETWORK

volumes:
  portainer_data:
```

`whoami` works fine.

Am I missing something? Or has something changed in the config files?
